App\Entity\Client:
    normalizationContext:
        groups: ['client:read']
    denormalizationContext:
        groups: ['client:write']
# App\Entity\Client:
#     operations:
#         ApiPlatform\Metadata\GetCollection:
#             normalizationContext:
#                 groups: ['client:collection:get']
#         ApiPlatform\Metadata\Post:
#             normalization_context:
#                 groups: ['client:item:get']
#             denormalization_context:
#                 groups: ['client:collection:post']
#         ApiPlatform\Metadata\Get:
#             normalization_context:
#                 groups: ['client:item:get']
#         ApiPlatform\Metadata\Delete: ~
#         ApiPlatform\Metadata\Put: ~
#         ApiPlatform\Metadata\Patch: ~
