App\Entity\Product:
    operations:
        ApiPlatform\Metadata\GetCollection:
            normalizationContext:
                groups: ['product:collection:get']
        ApiPlatform\Metadata\Get:
            normalization_context:
                groups: ['product:item:get']