App\Entity\User:
    normalizationContext:
        groups: ['user:read']
    denormalizationContext:
        groups: ['user:write']
# App\Entity\User:
#     operations:
#         ApiPlatform\Metadata\GetCollection:
#             normalizationContext:
#                 groups: ['user:collection:get']
#         ApiPlatform\Metadata\Post:
#             normalization_context:
#                 groups: ['user:item:get']
#             denormalization_context:
#                 groups: ['user:collection:post']
#         ApiPlatform\Metadata\Get:
#             denormalization_context:
#                 groups: ['user:item:get']