App\Entity\Client:
    attributes:
        id:
          groups: ['client:item:get', 'client:collection:get']
        username:
          groups: ['client:item:get', 'client:collection:get', 'client:collection:post', 'client:item:put', 'user:item:get']