App\Entity\Client:
    attributes:
        id:
          groups: ['client:read', 'client:write']
        username:
          groups: ['client:read', 'client:write', 'user:read']
        users:
          groups: ['client:read', 'client:write']
        password:
          groups: ['client:write']