App\Entity\User:
    attributes:
        id:
          groups: ['user:read', 'user:write']
        client:
          groups: ['user:read', 'user:write']
        name:
          groups: ['user:read', 'user:write']