App\Entity\User:
    attributes:
        id:
          groups: ['user:collection:get', 'user:item:get', 'user:collection:post']
        name:
          groups: ['user:collection:get', 'user:item:get', 'user:collection:post']